name: aws_polly
version: 2.1.1
description: A simple, unofficial AWS Polly client in dart. Supports generating a URL given an input text and voice identifier.
repository: https://github.com/robrichardson13/flutter_aws_polly

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.robrichardson.aws_polly
        pluginClass: AwsPollyPlugin
      ios:
        pluginClass: AwsPollyPlugin
